### ISSUE TITLE
code donation

### ISSUE THREAD

**Issue by Alloyed** [oniietzschan/terebi#1]
Thanks for putting in the work to make an actual library and actual tests and stuff <3

I write something more or less similar every time I make a pixel game, but because I'm an idiot I always rewrite in hacky, mutually incompatible ways. As a side effect tho it does have some nice features:
* canvas layers
* non-integer scaling (this works by rendering 'nearest' to a larger canvas than the window, and then downscaling it with 'linear')
* it used to have subpixel camera movement but I took it out for reasons I've already forgotten

Here's the code for so you can compare, or maybe steal features. Again, it's not super clear but if you have any questions about the API design or how it is implemented feel free to ask:
https://hastebin.com/eneguzapaf.lua

**Comment by oniietzschan** [comment]
Hey, thanks for writing!


Regarding your canvas layers: without a code example it's a bit difficult for me to understand what advantages having the library support layers might have. My usual approach would be to have my game manage different draw layers itself and render it all to one "native" canvas, and then have Terebi scale that canvas to whatever size is needed. Could you explain the advantages for me?

Non-integer scaling could be useful for some people. Although I feel that in almost every circumstance you'd get better visual quality by scaling graphics as they are drawn, rather than scaling the whole canvas at the end. One thing that occurs to me is that non-integer scaling becomes a much more natural thing to support if the public interface works through specifying a target output resolution, rather than a target scale factor. I'm not really sure which is better or more natural... I'll have to think about it!

I'm not sure if I'm interested in supporting sub-pixel stuff. Terebi doesn't really work through a camera system anyways, it just draws a canvas from (0, 0).

If nothing else, I think I'll definitely lift your `win2screen`, `screen2win`, and `mouse` methods. I usually end up having these for my games, I'm not sure why it never occurred to me to put them in the library itself.


Cheers!

PS: I started using loverocks last week and I'm definitely a fan! I was planning to suggest using loverocks in a little Installation section in my various libraries' READMEs!

**Comment by oniietzschan** [comment]
Since the original hastebin died, I'll go ahead and close this.

I ended up adding a few methods: `screen:getMousePosition()`, `screen:windowToScreen(windowX, windowY)`, and `screen:screenToWindow(gameX, gameY)`.

I've thought more about having multiple canvas layers and think it would be useful. However, I'm not sure what a clean interface for it would look like for it. Onceinspiration comes to me and I have a use for it, I'll add it.
